This notebook contains an excerpt from the Python Data Science Handbook by Jake VanderPlas; the content is available on GitHub.

The text is released under the CC-BY-NC-ND license, and code is released under the MIT license. If you find this content useful, please consider supporting the work by buying the book!

No changes were made to the contents of this notebook from the original.

# The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas (Chapter 3) are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book. Get to know them well!

We'll cover a few categories of basic array manipulations here:

- Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
- Indexing of arrays: Getting and setting the value of individual array elements
- Slicing of arrays: Getting and setting smaller subarrays within a larger array
- Reshaping of arrays: Changing the shape of a given array
- Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

# numpy array attributes

We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [3]:
np.random.seed(0) #seed for reproduciblity
X1=np.random.randint(10,size=6)#1 dimension array
X2=np.random.randint(10,size=(3,5))#2 dimensional array
X3=np.random.randint(10,size=(3,5,5))#3 dimensional array

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [6]:
print("X3 ndim: ", X3.ndim)
print("X3 shape:", X3.shape)
print("X3 size: ", X3.size)

X3 ndim:  3
X3 shape: (3, 5, 5)
X3 size:  75


Another useful attribute is the dtype, the data type of the array (which we discussed previously in Understanding Data Types in Python)

In [7]:
print('dtype:', X3.dtype)

dtype: int32


Other attributes include itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array:

In [9]:
print("itemsize:", X3.itemsize, "bytes")
print("nbytes:", X3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 300 bytes


In general, we expect that nbytes is equal to itemsize times size.

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the ith value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [10]:
X1

array([5, 0, 3, 3, 7, 9])

In [11]:
X1[0]

5

In [12]:
X1[4]

7

To index from the end of the array, you can use negative indices:

In [13]:
X1[-1]

9

In [14]:
X1[-5]

0

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [15]:
X2

array([[3, 5, 2, 4, 7],
       [6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5]])

In [16]:
X2[0]

array([3, 5, 2, 4, 7])

In [18]:
X2[(0,0)]

3

In [19]:
X2[0][0]

3

In [20]:
X2[2,4]

5

In [25]:
X2[-1,-1]

5

Values can also be modified using any of the above index notation:

In [27]:
X2[0, 0] = 12
X2

array([[12,  5,  2,  4,  7],
       [ 6,  8,  8,  1,  6],
       [ 7,  7,  8,  1,  5]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [29]:
X1[0] = 3.14159  # this will be truncated!
X1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]


If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.`m

## One-dimensional subarrays

In [32]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [35]:
x[5:]#last five elemnets

array([5, 6, 7, 8, 9])

In [36]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [37]:
x[::2]#select the evry second element

array([0, 2, 4, 6, 8])

In [38]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [39]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

## Multi-dimensional subarrays
Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example

In [41]:
X2

array([[12,  5,  2,  4,  7],
       [ 6,  8,  8,  1,  6],
       [ 7,  7,  8,  1,  5]])

In [43]:
X2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 6,  8,  8]])

In [46]:
X2[:, ::2]  # all rows, every other column

array([[12,  2,  7],
       [ 6,  8,  6],
       [ 7,  8,  5]])

In [47]:
X2[:3,::2] # all rows, every other column

array([[12,  2,  7],
       [ 6,  8,  6],
       [ 7,  8,  5]])

### Finally, subarray dimensions can even be reversed together:

In [48]:
X2[::-1,::-1]

array([[ 5,  1,  8,  7,  7],
       [ 6,  1,  8,  8,  6],
       [ 7,  4,  2,  5, 12]])

#### Accessing array rows and columns
One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [49]:
X2[:,2]# Third column of x2

array([2, 8, 8])

In [50]:
X2[0,:]#first row whith all columns in X2

array([12,  5,  2,  4,  7])

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [52]:
X2[0]# equivalent to x2[0, :]

array([12,  5,  2,  4,  7])

### Subarrays as no-copy views
One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [53]:
print(X2)

[[12  5  2  4  7]
 [ 6  8  8  1  6]
 [ 7  7  8  1  5]]


Let's extract a 2×2 subarray from this:

In [56]:
X2_sub=X2[:2,:2]
X2_sub

array([[12,  5],
       [ 6,  8]])

In [59]:
X2_sub[0,0]=99
X2_sub

array([[99,  5],
       [ 6,  8]])

In [60]:
X2

array([[99,  5,  2,  4,  7],
       [ 6,  8,  8,  1,  6],
       [ 7,  7,  8,  1,  5]])

This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays
Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:

In [62]:
X2_sub_copy=X2[:2,:2].copy()
X2_sub_copy

array([[99,  5],
       [ 6,  8]])

If we now modify this subarray, the original array is not touched:

In [64]:
X2_sub_copy[0,0]=66
X2_sub_copy

array([[66,  5],
       [ 6,  8]])

In [65]:
X2

array([[99,  5,  2,  4,  7],
       [ 6,  8,  8,  1,  6],
       [ 7,  7,  8,  1,  5]])

# Reshaping of Arrays
Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:

In [73]:
grid=np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

In [75]:
w=np.array([1,2,3])
# row vector via reshape
w.reshape((1, 3))

array([[1, 2, 3]])

In [79]:
vw=np.array([1,2,3])
# row vector via newaxis
vw[np.newaxis, :]

array([[1, 2, 3]])

In [80]:
# column vector via reshape
vw.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [82]:
# column vector via newaxis
vw[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting
All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.



### Concatenation of arrays
Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as we can see here:

In [83]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [84]:
z=np.array([33,44,55,66])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 33, 44, 55, 66])

It can also be used for two-dimensional arrays

In [85]:
grid=np.array([[6,5,4],
               [4,5,6]])

In [86]:
# concatenate along the first axis
np.concatenate([grid,grid])

array([[6, 5, 4],
       [4, 5, 6],
       [6, 5, 4],
       [4, 5, 6]])

In [87]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid,grid],axis=1)

array([[6, 5, 4, 6, 5, 4],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

In [88]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [89]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similary, np.dstack will stack arrays along the third axis.

In [93]:
a = np.array([[1],[10],[9]])
b = np.array([[2],[3],[4]])
np.dstack((a,b))


array([[[ 1,  2]],

       [[10,  3]],

       [[ 9,  4]]])

### Splitting of arrays
The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:

In [109]:
x = [1, 2, 3, 99, 99,3, 2, 1]
np.split(x,[3,5])


[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

Notice that N split-points, leads to N + 1 subarrays. The related functions np.hsplit and np.vsplit are similar:

In [98]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [104]:
left,right= np.hsplit(grid, [2])
print(left)


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [105]:
print(right)

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, np.dsplit will split arrays along the third axis